Server/sensor/urls.py
from django.conf.urls import url

from . import views

app_name = 'sensor'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^fire/$', views.fire, name='fire'),
	url(r'^tremor/$', views.tremor, name='tremor'),
]

Server/sibn/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^sensor/', include('sensor.urls')),
	url(r'^terminal/', include('terminal.urls')),
    url(r'^admin/', admin.site.urls),
]

Server/terminal/urls.py
from django.conf.urls import url

from . import views

app_name = 'terminal'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^logs/$', views.logs, name='logs'),
	url(r'^clear/$', views.clear, name='clear'),
]

Server/sensor/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Readings(models.Model):
	sensor_type = models.CharField(max_length=200)
	reading = models.IntegerField(default=0)
	time = models.DateTimeField('time recorded')
	def __str__(self):
		return self.sensor_type

Server/terminal/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
	uname = models.CharField(max_length=200)
	pwd = models.CharField(max_length=200)
	def __str__(self):
		return self.uname

Server/sensor/views.py
from django.shortcuts import render
from django.utils import timezone
from .models import Readings
# Create your views here.

def index(request):
	return render(request, 'sensor/index.html', context=None)


def fire(request):

	if request.method == "POST":
		read = request.POST['val']

		obj = Readings(sensor_type="Fire", reading=read, time=timezone.now())
		obj.save()

	return render(request, 'sensor/fire.html', context=None)


def tremor(request):

	if request.method == "POST":
		read = request.POST['val']

		obj = Readings(sensor_type="Tremor", reading=read, time=timezone.now())
		obj.save()

	return render(request, 'sensor/tremor.html', context=None)

Server/terminal/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import User
from sensor.models import Readings
# Create your views here.

def index(request):
	return render(request, 'terminal/index.html', context=None)

def logs(request):
	uname = request.POST['uname']
	pwd = request.POST['pwd']

	try:
		usr = User.objects.get(uname=uname, pwd=pwd)
	except User.DoesNotExist:
		return HttpResponse("<h1 style='color:red'>Incorrect Credentials</h1>")
	else:
		records = Readings.objects.all()
		return render(request, 'terminal/logs.html', context={'uname':uname, 'records':records})


def clear(request):
	records = Readings.objects.all()

	for obj in records:
		obj.delete()
	
	return HttpResponse("Logs Cleared")

Server/sensor/templates/sensor/fire.html
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <title>Fire Detector</title>
       <style>
            *{box-sizing: border-box;}

html
{
    height:100%;
    width:100%;
    
    
}


#inputReading
{
    height:32px;
    width:90%;
   margin:25px 10px 25px 15px;
}
button[type='submit']
{
    height:37px;
    width:90%;
      margin:0px 10px 25px 15px;
    float:left;
    
}

body
{
    background-color: #005F6D;
    background-size: cover;
    height:80%;
    width:80%;
    padding:10px;
}

form
{
    height:223px;
    width:20%;
    border-radius: 15px;
    color:whitesmoke;
   
    background-color: #91BF34;
    opacity:0.8;
    position:fixed;
    top:20%;
    right:40%;
     padding:25px 10px 10px 10px;
     border-radius: 15px;
}

label{
    height:22%;
    width:95%;
    color:whitesmoke;
    
        margin:10px 82px;
}

 
        </style>


  </head>

  <body>

      <form method="POST" action="{% url 'sensor:fire' %}"> {% csrf_token %}
        
        <label for="inputReading">Smoke level</label>
        <input type="number" id="inputReading" placeholder="Smoke Level" name="val" required autofocus>

        <button type="submit">Send</button>
      </form>

  </body>
</html>

Server/sensor/templates/sensor/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <title>SiBN - Sensor</title>
          <style>
            *{box-sizing: border-box;}

html
{
    height:100%;
    width:100%;
    
    
}



button
{
    height:37px;
    width:90%;
      margin:0px 10px 25px 15px;
    float:left;
    
}

body
{
    background-color: #005F6D;
    background-size: cover;
    height:80%;
    width:80%;
    padding:10px;
}

.wrapper
{
    height:223px;
    width:20%;
    border-radius: 15px;
    color:whitesmoke;
   
    background-color: #91BF34;
    opacity:0.8;
    position:fixed;
    top:20%;
    right:40%;
     padding:18px 10px 10px 10px;
     border-radius: 15px;
}

h2{
    height:22%;
    width:95%;
    color:whitesmoke;
    
        margin:10px 36px;
}

 
        </style>


  </head>

  <body>
        <div class="wrapper">
        <h2>Simulated Sensor</h2>
        <a href="{% url 'sensor:tremor' %}">
        	<button>Tremor Sensor</button>
        </a>
        <a href="{% url 'sensor:fire' %}">
        	<button>Fire Detector</button>
        </a>
        
        </div>

  </body>
</html>

Server/sensor/templates/sensor/tremor.html
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <title>Tremor Sensor</title>
         <style>
            *{box-sizing: border-box;}

html
{
    height:100%;
    width:100%;
    
    
}


#inputReading
{
    height:32px;
    width:90%;
   margin:25px 10px 25px 15px;
}
button[type='submit']
{
    height:37px;
    width:90%;
      margin:0px 10px 25px 15px;
    float:left;
    
}

body
{
    background-color: #005F6D;
    background-size: cover;
    height:80%;
    width:80%;
    padding:10px;
}

form
{
    height:223px;
    width:20%;
    border-radius: 15px;
    color:whitesmoke;
   
    background-color: #91BF34;
    opacity:0.8;
    position:fixed;
    top:20%;
    right:40%;
     padding:25px 10px 10px 10px;
     border-radius: 15px;
}

label{
    height:22%;
    width:95%;
    color:whitesmoke;
    
        margin:10px 65px;
}

 
        </style>

  </head>

  <body>

      <form method="POST" action="{% url 'sensor:tremor' %}"> {% csrf_token %}
        
        <label for="inputReading">Tremor Magnitude</label>
        <input type="number" id="inputReading" placeholder="Tremor Magnitude" name="val" required autofocus>

        <button type="submit">Send</button>
      </form>

  </body>
</html>

Server/terminal/templates/terminal/index.html
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>SiBN - Admin Signin</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <style>
            *{box-sizing: border-box;}

html
{
    height:100%;
    width:100%;
    
    
}
h2{
   margin:10px 10px 25px 50px;
}
#inputUsername
{
    height:32px;
    width:90%;
    margin:10px 10px 25px 10px;
}
#inputPassword
{
    height:32px;
    width:90%;
   margin:10px 10px 25px 10px;
}
button[type='submit']
{
    height:37px;
    width:90%;
    margin-left:10px;
    float:left;
    
}

body
{
    background-color: #005F6D;
    background-size: cover;
    height:80%;
    width:80%;
    padding:10px;
}

form
{
    height:340px;
    width:20%;
    border-radius: 15px;
    color:whitesmoke;
   
    background-color: #91BF34;
    opacity:0.8;
    position:fixed;
    top:20%;
    right:55%;
     padding:10px;
     border-radius: 15px;
}

label{
    height:22%;
    width:95%;
    color:whitesmoke;
    
        margin:20px 10px 10px 10px;
}

 
        </style>
    </head>
    <body>
        <div>
       <form method="POST" action="{% url 'terminal:logs' %}">{% csrf_token %}
        <h2>Please sign in</h2>
        <label for="inputusername">Username</label>
        <input type="text" id="inputUsername" placeholder="Username" name="uname" required autofocus>
        <label for="inputPassword">Password</label>
        <input type="password" id="inputPassword" placeholder="Password" name="pwd" required>

        <button type="submit">Sign in</button>
      </form>
        </div>
    </body>
</html>

Server/terminal/templates/terminal/logs.html
<!DOCTYPE html>
<html lang="en">
  <head>
  		<title>Browse Logs</title>
                      <style>
            *{box-sizing: border-box;}

html
{
    height:100%;
    width:100%;
    
    
}



body
{
    background-color: #005F6D;
    background-size: cover;
    height:80%;
    width:80%;
    padding:10px;
}



h1{
    height:22%;
    width:95%;
    color:whitesmoke;
    
        padding-left:350px;
        text-align: center;
}

table {
    width: 100%;
    text-align: center;
    padding: -1px;
    border: 2px solid black;
    width:124%;
}

th {
    height: 50px;
    background-color: #008000;
    color: #ffffff;
}

tr {
  height: 30px;
  background-color: #aaaaaa;
}
tr:nth-child(even) {background-color: #f2f2f2}

tr:hover {
  background-color: #000000;
  color: #ffffff;
}

        </style>

  </head>
  
  <body>
      
  	<h1>
  		Welcome, {{ uname }}
  	</h1>
  	
    {% if records %}
      <table>
        <tr>
          <th>Sensor Type</th>
          <th>Sensor Value</th>
          <th>Time recorded</th>
        </tr>
        {% for record in records %}
        
          

            <tr>
              <td>{{ record.sensor_type }}</td>
              
              <td
              {% if record.reading > 100 %}
                style="color:red; text-decoration:underline;"
              {% endif %}>
              {{ record.reading }}
              </td>

              <td>{{ record.time }}</td>
            </tr>
          
        {% endfor %}
      </table>
    {% else %}
      <h4 style="color:white; text-align:center; margin-left: 30%; ">No readings available.</h3>
    {% endif %}
  	

    <button><a href="{% url 'terminal:clear' %}">Clear Logs</a></button>
  </body>
</html>